### ISSUE TITLE
Page format for printing

### ISSUE THREAD

**Issue by tkisason** [OWASP/samm#1]
If someone wants to print the opensamm v.1.1 in A4 page size to give out as handouts in printed form, that's not really simple, since the current format is 2 pages per 1 physical page. Can you please upload a normally formatted opensamm documents, so if someone wants 2:1 layout like now, he can simply select that while printing. Reversing the current format from 2:1 to 1:1 layout is difficult. 

Thank you,
Tonimir Kisasondi

**Comment by SebaDele** [comment]
hi Tonimir,

thanks for raising this.
we have fixed this issue, 1:1 layout files are now available as 1 page versions.

regards
Seba

**Comment by tkisason** [comment]
Excelent. Thank you, i like to hand out printed versions of SAMM and ASVS, so this helps!
