### ISSUE TITLE
slack input

### ISSUE THREAD

**Issue by SebaDele** [OWASP/samm#100]
https://owasp.slack.com/archives/GEUR73PL1/p1546029791018700
My fifth point: I think the introduction text on owaspsamm.org is too much about measuring and assurance. It should also be about the great guidance it provides to developers and security professionals in making software security work, as it is an interplay between many different activities.

**Comment by SebaDele** [comment]
to be taken into account for the new website

**Comment by 23bartman** [comment]
IMO this is reasonably represented on the website. I'm closing this one.
