### ISSUE TITLE
consider not requiring definitive timeframes (Slack input)

### ISSUE THREAD

**Issue by SebaDele** [OWASP/samm#102]
https://owasp.slack.com/archives/C0VF1EJGH/p1553270328032500
When writing practices, consider not requiring definitive timeframes (e.g., 6 months) or phrasing timeframes more flexibly (e.g., periodically as appropriate). I find that myself and the developers I interview take these descriptions rather literally, and in some cases,  the wording implies you only get credit if you meet the timeframe requirements exactly. I have modified wording in several cases to make the interviews flow more quickly and smoothly.

**Comment by SebaDele** [comment]
@Pat-Duarte can you check this while reviewing? thx

**Comment by Pat-Duarte** [comment]
What we have in some of the questions is yearly. We can keep that one, right @SebaDele?

**Comment by SebaDele** [comment]
right!

**Comment by 23bartman** [comment]
This has been taken into account in version 2.0, and it's part of the writing guidelines (if I'm not mistaking). I'm closing this one.
