### ISSUE TITLE
The operation functions of third party vendor

### ISSUE THREAD

**Issue by paulur** [OWASP/samm#109]
We have 3rd party vendors providing us products, including embedded software and hardware where the embedded software is deployed. Both software and hardware will run in our customers' environment. It seems to us that practices of operation functions, particularly environment hardening and operational environment, are not applicable to the vendors. Wondering if we should remove these practices from evaluation, or we should evaluate these practices of vendors  regardless where our products are running.

**Comment by paulur** [comment]
Any update for this issue? Thanks, Paul

**Comment by dkefer** [comment]
If some practices are not applicable, I'd remove them from the assessment.
