### ISSUE TITLE
Define the new measurement model

### ISSUE THREAD

**Issue by 23bartman** [OWASP/samm#111]
Take into account:
- coverage vs. quality
- CMMI levels
- people / process / technology
- feedback Peter Debasse
- COBIT
- IMM
- ...

**Comment by 23bartman** [comment]
Inspiration on defining the levels:
https://www.nao.org.uk/wp-content/uploads/2016/11/Performance-Measurement-Good-practice-criteria-and-maturity-model.docx

**Comment by 23bartman** [comment]
Multi-dimensional modelling in TMSMM:
https://www.intechopen.com/books/telemedicine/the-telemedicine-service-maturity-model-a-framework-for-the-measurement-and-improvement-of-telemedic

**Comment by 23bartman** [comment]
Dinis' feedback: use the community to drive the questions ...

**Comment by yanfosec** [comment]
@23bartman or @SebaDele - Perhaps we should summarize our decision to move forward with the scoring model to help close the ticket and have something we can reference.

**Comment by SebaDele** [comment]
done
