### ISSUE TITLE
Review and Revise Threat Assessment Practice

### ISSUE THREAD

**Issue by johndileo** [OWASP/samm#117]
During the initial question-writing effort for the Threat Assessment Practice, the following issues were noted with the latest revision of the narrative:

* Stream A, Maturity 1:
** The first paragraph seems like it belongs in an overview, either for the Practice or for the Stream
** The last paragraph (a single sentence) summarizes the preceding two paragraphs, and is probably unnecessary
* Stream A, Maturity 3: The narrative does not mention the expected "feedback loop" for the process
* Stream B, Maturity 1:
** The first two paragraphs are an overview of Threat Modeling's purpose, and could be moved into an overview section for the Stream
** The narrative for Maturity 1 should explicitly mention the informal nature of linking Threat Model outputs to development workload/backlog
* Stream B, Maturity 2: This is the first mention of training - shouldn't there be some level of training at Maturity 1?
* Stream B, Maturity 3: There were questions raised about the meaning of all three paragraphs - clarify and expand

**Comment by SebaDele** [comment]
ok for stream A, for stream B see issue #174
