### ISSUE TITLE
Application Risk profile

### ISSUE THREAD

**Issue by 23bartman** [OWASP/samm#118]
Level 1 = basic yes/no questions
Level 2 = similar to BIA with more in-depth analysis on potential risk (possibly link to financial impact)
Clarify this in the description

**Comment by 23bartman** [comment]
An organization could only do level 1 and 3 in practice. Does this make sense ?

**Comment by SebaDele** [comment]
more emphasis on the phrase: "This inventory gives all stakeholders an aligned view of the risk level of an application to assign appropriate priority to security-related activities."
1) add accountability for the application security classification
2) agreed upon security activities based on the application security classification: e.g. a security source code review is mandatory for High risk applications.

L2: add the business and BIA impact as part of the classification.
review if quantification is necessary (and review the amount of text versus the overall text).

**Comment by johnellingsworth** [comment]
#212
