### ISSUE TITLE
Restructure Secure Deployment Stream A

### ISSUE THREAD

**Issue by itscooper** [OWASP/samm#123]
Activity stream A does not flow well, and the activities are not progressive. Furthermore, the maturity levels are not consistent with Secure Build despite having similar properties.

A proposal:

Maturity 1. Can be manual - focus is on access to production (polp, responsibility)
Maturity 2. Automation - integrate security checks
Maturity 3. Baseline to prevent deployment, and automated verification of artifacts

**Comment by itscooper** [comment]
N.b. Developers shouldn't be able to directly edit code in prod? Pre-agree lifecycle/process (CI). Oversight.

**Comment by itscooper** [comment]
Whether you doing SAST or DAST well is part of security testing. Whether you are integrating is part of implementation. Separation.

We need to make sure that non-devops (e.g. 4m lines of code) scenarios are catered for. E.g. where SAST has to be done out of band.

**Comment by SebaDele** [comment]
covered with the current version
