### ISSUE TITLE
Revise integrity checks in secure build and deployment

### ISSUE THREAD

**Issue by itscooper** [OWASP/samm#124]
A proposal for different maturity requirements for generating integrity values and verifying them...

 ```
  Build				    Deployment
1. hash or code sign	    -
2. code sign for ext only	    Verify integrity
3. code sign ext and int	    Verify signature
```

**Comment by itscooper** [comment]
Split responsibility model.

You sign a mobile app. App store's responsibility to verify. 

Maybe change build to...
1. Hash
2. Code sign - proof is hard-linked to artifact - and auth'd
3. Deterministic - build process itself has integrity

**Comment by itscooper** [comment]
Hashing and code signing should be examples - describe their properties (e.g. hard linked to artifact)

**Comment by SebaDele** [comment]
linked to #150 - make sure to cross-check

**Comment by dkefer** [comment]
Stream adapted
