### ISSUE TITLE
Availability during deployment

### ISSUE THREAD

**Issue by itscooper** [OWASP/samm#130]
From DevSecOps maturity model.

Deployment process meets the organization's security requirements in terms of availability. I.e. ig the org requires high availability, rolling updates are possible without downtime. Maturity 1.

**Comment by dkefer** [comment]
Edited description of 1st level of Secure Deployment stream (given that the hardening of the used tooling is discussed there): "Choose any tools used during deployment carefully and harden them appropriately, including ensuring defined availability requirements (possibly leading e.g. to a redundant setup)."
