### ISSUE TITLE
Security Requirements - Software Requirements - Maturity 2 (Bart)

### ISSUE THREAD

**Issue by sebarriada** [OWASP/samm#135]
The goal and benefit for this section should be review and aligned to the systematic way of gathering requirements:
Security Requirements - Software Requirements - Maturity 2 (Bart)

**Comment by johnellingsworth** [comment]
Updated benefit to _"Relevant security requirements gathered in a structured format provide a prioritized, detailed understanding of attack scenarios against business logic."_
