### ISSUE TITLE
clearly indicate the assessment checklist for v2.0 is not usable yet

### ISSUE THREAD

**Issue by nessimk** [OWASP/samm#142]
Although the checklist is available for download under the supporting resources of v2.0, it is not actually usable as the questions are still those of v1.5 (the ones from v2.0 haven't yet been completed).  We should clearly indicate this somewhere to avoid people wasting their time using what *looks* like a ready tool.

I suggest removing it from the downloads for v2.0. If we think it still has some value in its current form, we should add a big warning to the first sheet.

**Comment by SebaDele** [comment]
that particular checklist is not present anymore in the 2.0 folder on github
