### ISSUE TITLE
Rephrasing suggested for question: Threat Assessment 3/3 

### ISSUE THREAD

**Issue by DavidCervigni** [OWASP/samm#146]
The suggested version allows not to contradict the question with any answer: e.g. "are the majority" > Yes, a small percentage

Original:
Are the majority of the protection mechanisms and controls captured and mapped back to threats? | Yes, a small   percentage are/do

Suggestion:
Are the protection mechanisms and controls captured and mapped back to threats? 
| Yes, a small   percentage are/do

**Comment by SebaDele** [comment]
correct feedback, in the new version 2.0 this question completely changed.
we do not fix SAMM1.5 anymore
