### ISSUE TITLE
owaspsamm.org homepage needs SAMM defined

### ISSUE THREAD

**Issue by johnellingsworth** [OWASP/samm#157]
Feedback received that what the SAMM acronym stands for is not clearly stated on the owaspsamm.org web site.  Can we include "Software Assurance Maturity Model" on the page?  Perhaps something like this:

"The prime Software Assurance Maturity Model (SAMM) that provides an effective and measurable way for all types of organizations to analyse and improve their software security posture."

**Comment by cdikibo** [comment]
Is this something I can possibly do? @johnellingsworth

**Comment by Pat-Duarte** [comment]
@SebaDele do you mean for the new website or the current one? I've already considered that for the new one.
![image](https://user-images.githubusercontent.com/41348252/69481488-9026de80-0df0-11ea-9b14-4a501c448e00.png)
