### ISSUE TITLE
Toolbox not calculating correctly

### ISSUE THREAD

**Issue by 23bartman** [OWASP/samm#160]
In the current version of the toolbox, the roadmap tab, the maturity scores are not correctly calculated. This is due imo to an incorrect link to the set of answers to the questions, which results in the hidden cells not properly being updated. Please have a look into this.

**Comment by johnellingsworth** [comment]
Hi Bart.  I reviewed the issue and it appears that @SebaDele deleted the version I committed and uploaded a version with some issues.  Bad Seba!  :-)

Attached is the refined version, cleaned up and made pretty.  We can discuss during today's call.
[SAMM_Assessment_Toolbox_v2.0.xlsx](https://github.com/OWASP/samm/files/3708869/SAMM_Assessment_Toolbox_v2.0.xlsx)

**Comment by SebaDele** [comment]
fixed now
