### ISSUE TITLE
explain *AST tooling in Security Testing practice

### ISSUE THREAD

**Issue by SebaDele** [OWASP/samm#162]
Include IAST everywhere that SAST and DAST are mentioned?
Or explain *AST in maturity level and use a pointer to the security testing section where this is used?

**Comment by SebaDele** [comment]
explain *AST in maturity level and use a pointer to the security testing section where this is used?

**Comment by nessimk** [comment]
Done, part of commit c3a54d9024638569a528f9af5ed3ffe7cf0745b3
