### ISSUE TITLE
rename "requirements driven testing" to "requirements testing"

### ISSUE THREAD

**Issue by SebaDele** [OWASP/samm#184]
align on 2 word practice naming

**Comment by SebaDele** [comment]
the content is not yet updated.
e.g. name
also to be updated in the toolbox

**Comment by SebaDele** [comment]
updated the toolbox 2.0 template

**Comment by Pat-Duarte** [comment]
Resolution: not to migrate
We hyphenated the name and changed it to Requirements-driven Testing
