### ISSUE TITLE
Manually apply Yan's pull request

### ISSUE THREAD

**Issue by 23bartman** [OWASP/samm#204]
Make sure that all the quality improvements are covered in the text.

**Comment by yanfosec** [comment]
At this point there is no reason to merge these changes... all MD files were moved to YAML.

I will try to do similar consistency checks on the YAML side, but sounds like it might be well in hand with Pat's help.

**Comment by 23bartman** [comment]
That was indeed the idea - not litteraly apply the pull request, but see what is still relevant in the current YAML files ...
