### ISSUE TITLE
Referencing Practice names in description

### ISSUE THREAD

**Issue by johnellingsworth** [OWASP/samm#224]
Should we standardize on references to Practice names in long description copy?  

Some Practice descriptions examples:
_The Policy & Compliance (PC) Practice focuses on_
_The Secure Build practice emphasises_
_The security architecture practice focuses on_
_Incident Management security practice describes_
_The Education & Guidance (EG) Practice focuses on_

Some have no reference to the Practice in the long description.

**Comment by Pat-Duarte** [comment]
Yes, thank you for the input.

I'm not sure if many are using abbreviations in the rest of the description. If that's the case, we may want to keep them. I'll review that when I start reading them in full.

I added the following to the guidelines:

Refer to the practice by its name. 
Don’t capitalize the word “practice”.
Example: The Threat Assessment practice...

**Comment by 23bartman** [comment]
Part of the guidance, and it's consistent in our descriptions AFAIK. I'm closing this one.
