### ISSUE TITLE
Input on SAMM-Model-v2.00 apha

### ISSUE THREAD

**Issue by nocomplexity** [OWASP/samm#24]
Dear all,
Great work!! In the attachment some remarks to make it better.

[SAMM-Model-v2.00 alpha release_review-by-NOCOMPLEXITY.com.xlsx](https://github.com/OWASP/samm/files/1883306/SAMM-Model-v2.00.alpha.release_review-by-NOCOMPLEXITY.com.xlsx)

Regards, Maikel

**Comment by 23bartman** [comment]
Many thanks for your feedback. With our version 2.0 released, we hope we have covered many of your concerns. We would welcome any feedback you might have on the latest version ! Kind regards, Bart.
