### ISSUE TITLE
Add TOC to the PDF

### ISSUE THREAD

**Issue by 23bartman** [OWASP/samm#243]
As discussed, add a TOC to the current PDF

**Comment by nessimk** [comment]
Done although in a roundabout manner.
I got wkhtmltopdf to generate a toc but could not convince it to render it as a page we could insert into the PDF. The current solution dumps the toc generated by wkhtmltopdf, creates a pdf page out of it then prepends it to the pdf again as a regular page. 

While this works and I will close the issue, we should find a cleaner way of doing this when there's more time.
