### ISSUE TITLE
Is http://www.opensamm.org still an official site

### ISSUE THREAD

**Issue by nhajiyani** [OWASP/samm#4]
If yes then its highly outdated - I will be happy to help update it.
If no then would be worth adding the link to the OWASP wiki site on the homepage itself as that site bubbles up in the google search and folks may not realize that there are newer versions for the model out there.

**Comment by infosecdad** [comment]
It's an official site for OpenSAMM v1.0, but not for OWASP SAMM v1.1, v1.5, etc.  We have been working with the site owner to get a note/link/verbiage placed on opensamm.org to help with the confusion.  Hopefully not too much longer.  Thanks!

**Comment by thomaskonrad** [comment]
On the website, the downloads section points to SAMM v1.0, which is of 2009. https://www.owasp.org/index.php/OWASP_SAMM_Project points to 1.5.

This is indeed very confusing. Please reopen this issue.

**Comment by thomaskonrad** [comment]
Oh, I just realized there is both https://www.opensamm.org (old) and https://owaspsamm.org (new). That's even more confusing!

Why not make the first one redirect to the second one?
