### ISSUE TITLE
Align practice level goal descriptions

### ISSUE THREAD

**Issue by nessimk** [OWASP/samm#412]
The text of the goals for the different practice levels is currently too varied which is problematic for both the pdf and (to a lesser extent) the website.

Here's an illustration of the problem for the PDF:
![goals](https://user-images.githubusercontent.com/29360986/74378843-f6674000-4de6-11ea-9c4e-cf89aa50e50d.png)

For the website, compare the goals of these 2 practices:
  - https://owaspsamm.org/model/operations/operational-management/ 
  - https://owaspsamm.org/model/design/security-requirements/

**Comment by 23bartman** [comment]
This has been fixed in version 2.0
