### ISSUE TITLE
SAMM homepage linking of agile notes broken (404)

### ISSUE THREAD

**Issue by sofarsoghood** [OWASP/samm#418]
The agile notes should be available under https://owaspsamm.org/head/agile-guidance/agilenotes/ (as mentioned in **[this](https://github.com/OWASP/samm/blob/master/Current%20Releases/head/agile-guidance/agilenotes.md)** markdown file) but aren't (404).

**Comment by Abdoadnan** [comment]
Any updates on this issue?

**Comment by robvanderveer** [comment]
Yes. It has been fixed by incorporating the guidance in the guidance menu. Also the md has been updated. Next step is to add the ability to create links from elements of the core model to sections in the guidance. This issue can be closed.
