### ISSUE TITLE
Download links not aligned / poor readability

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/samm#426]
At https://owasp.org/www-project-samm/, download sections ("Download v1.5" / "Download v1.1.1"), links are not aligned, making it difficult to read + understand what items can be retrieved from there (6 / 4, but I had to spend extra time to figure that out). 

![image](https://user-images.githubusercontent.com/25180888/76506941-40762c80-644c-11ea-8759-67aec0e67798.png)

**Comment by 23bartman** [comment]
@Pat-Duarte Could you have a look into this one ? Thx !

**Comment by Pat-Duarte** [comment]
@23bartman 
This is related to the project page on the OWASP website. 
https://owasp.org/www-project-samm/
I don't have access to that. Maybe assign to @SebaDele.

**Comment by 23bartman** [comment]
I reassigned this one to SebaDele.

**Comment by Pat-Duarte** [comment]
Resolution: not to migrate
Fixed on the OWASP website
