### ISSUE TITLE
Interview option that should be reviewed/changed

### ISSUE THREAD

**Issue by kostasadriano** [OWASP/samm#427]
Hi,
in SAMM_Assessment_Toolbox_v2.0.xlsx,, for line 194 "Do you review and update the incident detection process regularly?"
the following answer options don't seem correct: Yes, for some applications , etc

In Data Validity, F194 is AnsF . AnsT seems more appropriate, so the options will be 
No
Yes, but we improve it ad-hoc
Yes, we we improve it at regular times
Yes, we improve it at least annually

**Comment by 23bartman** [comment]
@John, could you have a look into this one ? Thx !
