### ISSUE TITLE
Typo SAMMv 2 blog

### ISSUE THREAD

**Issue by SebaDele** [OWASP/samm#430]
I think you have a grammatical error in you SAMM landing page: I think it should be "that" not "they"

URL: https://owaspsamm.org/blog/2020/01/31/samm2-release/

OWASP SAMM (Software Assurance Maturity Model) is the OWASP framework to help organizations assess, formulate, and implement, through our self-assessment model, a strategy for software security ==> they <== can be integrated into their existing Software Development Lifecycle (SDLC).

**Comment by Pat-Duarte** [comment]
Indeed, there's a mistake.
This is what we're going for:
a strategy for software security they can ==> integrate <== into their existing
