### ISSUE TITLE
404 link on the website

### ISSUE THREAD

**Issue by SebaDele** [OWASP/samm#436]
see https://owaspsamm.org/guidance/quick-start-guide/
in the how-to "Implement" tab there is a link to https://owasp.org/index.php/SAMM-Resources which gives a HTTP 404 - Page Not Found.
to be fixed?

**Comment by Pat-Duarte** [comment]
I'm using this issue to fix all instances of links and mentions to the old OWASP wiki. I'm calling it "SAMM project page - OWASP website".
- 5 links on the quick start guide
- 1 link on the v1.5 page
- mentions on the sponsors page
