### ISSUE TITLE
Upgrade kind-of depedency on samm app

### ISSUE THREAD

**Issue by fzipi** [OWASP/samm#456]
1 kind-of vulnerability found in …/server/package-lock.json on Apr 14
Remediation

Upgrade kind-of to version 6.0.3 or later. For example:

"dependencies": {
  "kind-of": ">=6.0.3"
}

or…

"devDependencies": {
  "kind-of": ">=6.0.3"
}

Always verify the validity and compatibility of suggestions with your codebase.

**Comment by fzipi** [comment]
@sath9600 Can you upgrade this please?

**Comment by sath9600** [comment]
Successfully, Upgraded the **kind-of** module to the latest version 6.0.3
