### ISSUE TITLE
Ensure Consistency and Appropriate Division Between 3rd Party Software Activity Streams

### ISSUE THREAD

**Issue by itscooper** [OWASP/samm#47]
Affected streams:
- o-environment-management
- i-secure-build
- d-security-architecture

Lots of cross-over relating to the management of 3rd party software. We need to make sure there are clear divisions to reduce overlap, but also make sure that the requirements at each maturity level are in-line with each other because they are all similar.

**Comment by SebaDele** [comment]
converted into secure build - stream B
