### ISSUE TITLE
Web Markdown Image and Icon issue in contributing.md file

### ISSUE THREAD

**Issue by sath9600** [OWASP/samm#479]
Hi Pat,

Please look into "samm/Website/content/contributing.md"  There is a **production build** error on running workflow jobs. Mistakenly pushed my code without pulling.

![image](https://user-images.githubusercontent.com/9526255/86919704-47852100-c146-11ea-9d90-a2bb0c8b187f.png)

**Comment by Pat-Duarte** [comment]
@sath9600 Did you create a branch for this?

**Comment by sath9600** [comment]
No branchings, committed to master.

**Comment by Pat-Duarte** [comment]
I fixed everything in the Website folder. We also changed permissions so nobody pushes to master.

Make sure you follow our guidelines for further contributions.
1. Create a branch from our repository
2. Make changes and push the branch to GitHub
3. Create a pull request and add someone in the SAMM core team as a reviewer
Once the changes are approved, someone from the team will merge that branch to the master branch.

Please, take a look at these for more info:
https://owaspsamm.org/contributing/ 
https://owaspsamm.org/blog/2020/03/31/samm-is-doing-cicd/

Thanks!
