### ISSUE TITLE
Bug Bounties

### ISSUE THREAD

**Issue by itscooper** [OWASP/samm#48]
@SebaDele what do you think about including bug bounties somewhere? I don't think we've discussed them as far as I can think. Asking you as verification _might_ be the right place, but I'm not sure. It's often considered an alternative to pentesting (activity stream B). 

On the other hand, I suppose its something you do after you've done live? So it more to do with operations? Or are there reasons to leave it out entirely?

What do you think?

**Comment by SebaDele** [comment]
to be mentioned in security testing - B2

**Comment by nessimk** [comment]
Done. New text part of commit c3a54d9024638569a528f9af5ed3ffe7cf0745b3
