### ISSUE TITLE
Maybe separate software supplier and software consumer activities into separate streams

### ISSUE THREAD

**Issue by itscooper** [OWASP/samm#53]
E.g. patching of your own environment vs pushing patches to your customers
Or handling software lifecycles (support / legacy) in your own environment vs documenting and communicating your own software's lifecycles to your customers

**Comment by SebaDele** [comment]
to address in guidance part. the model itself does not take into account if the activity is done by a "supplier" or "customer".

**Comment by SebaDele** [comment]
also see #51

**Comment by 23bartman** [comment]
For version 2.0, we have further discussed, but agreed not to do this, as this might complicate the model too much. I'm closing this topic ; both are covered in the description.
