### ISSUE TITLE
home URL has a default template header,

### ISSUE THREAD

**Issue by SebaDele** [OWASP/samm#535]
currently the SAMM home URL has a default template header, resulting in "Site template made by devcows using hugo" when inserting an OWASP SAMM link in e.g. Slack.

@Pat-Duarte - can the page headers (at least the home page) contain relevant information instead of the template language?

**Comment by Pat-Duarte** [comment]
Absolutely! 
@SebaDele, Would "Software Assurance Maturity Model" be ok?

**Comment by Pat-Duarte** [comment]
@SebaDele 
Another option: Analyze and improve your organization's software security posture

**Comment by SebaDele** [comment]
I prefer:
Measure and improve your organization's software security posture
