### ISSUE TITLE
/events with broken links

### ISSUE THREAD

**Issue by wurstbrot** [OWASP/samm#580]
In the newsletter, the page https://owaspsamm.org/blog/2021/11/30/owasp-samm-train-the-trainer/ is highlited. The "events" page is highlited on the bottom on the article.

The events pages lists:
- OWASP SAMM: Status and Roadmap: The link leads to a 404
- Secure your SDLC using OWASP SAMM - ASAP!: Leads to https://training.owasp.org/, which is confiusing because I get to see OWASP Top Ten Trainings which are not related to SAMM

**Comment by Pat-Duarte** [comment]
We're removing these old events from the events page
