### ISSUE TITLE
Discuss secure design guidelines somewhere (e.g., proper input validation)

### ISSUE THREAD

**Issue by 23bartman** [OWASP/samm#63]
See Minneapolis discussion (https://docs.google.com/document/d/1ictH4Y4YGK8N9455y497FEx6CdmSzxh4QnzMnAaMrt0/edit#), the part on security requirements.

**Comment by SebaDele** [comment]
covered by policy & compliance - A - L1 - "Standards require input from senior developers and architects considered experts in various technologies in use by the organization. "  ? Consider as guidance.
