### ISSUE TITLE
improve/simplify document structure

### ISSUE THREAD

**Issue by SebaDele** [OWASP/samm#65]
input from @robvanderveer: With respect to the downloads: people don’t know where to start. Perhaps they start with the start guide. But that document does not describe the other documents. It doesn’t even mention the core model. For an outsider, the term ‘core model’ is unclear and perhaps comes across a bit academic. Perhaps it’s better to call this the main document, or something.

**Comment by Pat-Duarte** [comment]
Resolution: not to migrate
We don't have multiple downloads for v2 and we call the model "the model", not core model.
