### ISSUE TITLE
distinction between requirements driven testing and security testing is unclear

### ISSUE THREAD

**Issue by SebaDele** [OWASP/samm#66]
The distinction between requirements driven testing and security testing is unclear. They overlap and the sections seem to have been written by different people with an overlap in intentions. 
It’s hard for me to see the intention behind the split. Based on what I read and what I know I’d say: make it into one topic. (from @robvanderveer )

**Comment by SebaDele** [comment]
explain distinction and intent better in both security practice descriptions

**Comment by nessimk** [comment]
Reworked the test as part of commit c3a54d9024638569a528f9af5ed3ffe7cf0745b3
