### ISSUE TITLE
peer review /expert code review vs SAST

### ISSUE THREAD

**Issue by SebaDele** [OWASP/samm#68]
I believe that v-security-testing.md suggests wrongfully that SAST tools will do the trick. There is too little description of peer review /expert code review. I almost miss the old ‘implementation review’ section. (from @robvanderveer )

**Comment by SebaDele** [comment]
make manual security testing more explicit.

**Comment by nessimk** [comment]
Reworked parts of the text. part of commit c3a54d9024638569a528f9af5ed3ffe7cf0745b3
