### ISSUE TITLE
Page breaks cut of elements on printed pages

### ISSUE THREAD

**Issue by wurstbrot** [OWASP/samm#75]
When I print /v2.0b/core/governance/g-strategy-metrics/, "Maturity 2" is not showing up. I guess due to the page break.
Also, the table headers are cut of, when a page breaks happens, e.g. Policy & Compliance Overview-Table.
This might be important in relation to PDF generation (https://github.com/OWASP/samm/issues/70).

**Comment by SebaDele** [comment]
cannot be reproduced. a separate pdf generation will be used for the model
