### ISSUE TITLE
Other word for Threshold

### ISSUE THREAD

**Issue by wurstbrot** [OWASP/samm#86]
In https://github.com/OWASP/samm/blob/master/Current%20Releases/head/core/implementation/i-defect-management.md a threshold is mentioned.
I associate a threshold with a number. In the OWASP Dependency Check Jenkins Plugin you are able to set a "threshold" for different criticalities (low/medium/high) of vulnerabilities. In case there are more than X vulnerabilities, the build has the status broken/unstable.
Unfortunately, I do not have a better suggestion (right now).

**Comment by itscooper** [comment]
@Pat-Duarte I think I agree with @wurstbrot that the word threshold is poor. As an example, if you rate vulnerability severity on a 1-5 scale, you would decide that anything 4 or over is unacceptable. I was referring to this as a 'threshold', but I'm having a mental bock as to a word that is both simple and concise. In case you have any thoughts.

**Comment by SebaDele** [comment]
this word is commonly used and in this context correctly reflects the meaning of the word threshold (https://dictionary.cambridge.org/dictionary/english/threshold)
we could further clarify on what the threshold applies.

**Comment by dkefer** [comment]
Activity descriptions refactored, the word "threshold" is not used anymore.
