### ISSUE TITLE
SD2 Question in Assessment

### ISSUE THREAD

**Issue by sparticvs** [OWASP/samm#89]
The Question:
```
Do configuration files not contain unencrypted sensitive configuration information?
```

The answer "No" for the default "bad" case can be misinterpreted. It could be "No, we don't have unencrypted data. I believe the question should be worded as:

```
Are configurations files free of unencrypted sensitive configuration information?
```

**Comment by nessimk** [comment]
I came to the same conclusion and updated it while fixing other things. I'll push a fixed version when done.

**Comment by SebaDele** [comment]
this is covered in the new version
