### ISSUE TITLE
Question on SD2 (DougM via Slack)

### ISSUE THREAD

**Issue by 23bartman** [OWASP/samm#90]
Question, I'm not quite sure how to interpret this one: SD2 Is integration of security verification in deployment performed (e.g. binary static code analysis / AV scan)?    
So is this intended to validate that the code you built is what you placed into production? So for example code signing would help as well? If so is the AV scanning intended to look for malicious code someone managed to sneak in? It just seems that binary static (SAST) and AV are very different and I don't quite get the underlying idea on this one.

**Comment by itscooper** [comment]
My original replies on Slack, for reference:

> I think DAST and A/V are being used as examples of ways that issues can automatically be detected in binaries that have already been built and are currently being deployed. For example, if your application pulls in dependencies which build to a binary that matches a malware signature, this will be picked up during deployment. Some vulnerability scanners (e.g. Nessus)  can also check files against malware signatures. I don't think this specifically relates to the integrity of the code. Also, I think AV was suggested as an addition when we originally just had DAST as the example. Does that make sense and what's you're opinion?

> Also, there's some discord because the summary says "binary static code analysis / AV scan" and the text says "such as DAST and malware scanning"

**Comment by SebaDele** [comment]
update "Deployments include appropriate automated security checks such as DAST and malware scanning" to "Deployments include appropriate automated security checks such as DAST and vulnerability scanning"

update title - remove "(e.g. binary static code analysis / AV scan)."

**Comment by dkefer** [comment]
Description adapted.
