### ISSUE TITLE
slack feedback dependencies

### ISSUE THREAD

**Issue by SebaDele** [OWASP/samm#92]
https://owasp.slack.com/archives/C0VF1EJGH/p1553045949021200
IMO, the maturity items for dependencies (known vulns and license issues) is really weak and should be the minimum. More mature organizations should be adopting strategies and recommendations listed https://www.owasp.org/index.php/Component_Analysis

**Comment by SebaDele** [comment]
consider input to improve stream Software Dependencies

**Comment by SebaDele** [comment]
consider the section "Recommendations" of listed reference as quality criteria for questions

**Comment by dkefer** [comment]
Stream adapted.
