### ISSUE TITLE
slack feedback

### ISSUE THREAD

**Issue by SebaDele** [OWASP/samm#97]
https://owasp.slack.com/archives/C0VF1EJGH/p1548865919071200
Beta feedback: I come from a world where guidance needs to be auditable. Suggest collapsing activities into crisp bullets of actionable “shall” and “should” statements”, ideally with an eye toward increasing automation while still remaining tool agnostic. Also, it seems we are recommending artifacts without being explicit (ex. “..interview business owners and stakeholders and document drivers..“). I would push the example by asking, “Is email documentation therefore a good enough software security practice?“.

**Comment by 23bartman** [comment]
Duplicate with #91
