### ISSUE TITLE
slack question 

### ISSUE THREAD

**Issue by SebaDele** [OWASP/samm#99]
https://owasp.slack.com/archives/C0VF1EJGH/p1546988673017400
Question, I'm not quite sure how to interpret this one: SD2 Is integration of security verification in deployment performed (e.g. binary static code analysis / AV scan)?    
So is this intended to validate that the code you built is what you placed into production? So for example code signing would help as well? If so is the AV scanning intended to look for malicious code someone managed to sneak in? It just seems that binary static (SAST) and AV are very different and I don't quite get the underlying idea on this one.

**Comment by 23bartman** [comment]
This is a duplicate of issue #92
